package hasim;

public enum CounterTag {

	MAP_INPUT_RECORDS, 
	MAP_OUTPUT_RECORDS,
	MAP_SKIPPED_RECORDS,
	
	MAP_INPUT_SIZE, 
	MAP_OUTPUT_SIZE,
	
	COMBINE_INPUT_RECORDS,
	COMBINE_OUTPUT_RECORDS,
	
	COMBINE_INPUT_SIZE,
	COMBINE_OUTPUT_SIZE,

	REDUCE_INPUT_GROUPS,
	REDUCE_SHUFFLE_SIZE,
	REDUCE_INPUT_RECORDS,
	REDUCE_OUTPUT_RECORDS,
	REDUCE_SKIPPED_GROUPS,
	REDUCE_SKIPPED_RECORDS,
	
	SPILLED_RECORDS, 
	START_TIME,STOP_TIME
}

